version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  deploy-ecr:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: tf-ecr/
      - terraform/validate:
          path: tf-ecr/
      - terraform/plan:
          path: tf-ecr/
      - terraform/apply:
          path: tf-ecr/
  docker-build-push:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          tag: "${CIRCLE_SHA1},latest"
          path: "docker/"
          ###########################################################
          ### LACEWORK AGENT SUPPORT ###  Pass in the agent token ###
          ###########################################################
          extra-build-args: "--build-arg LW_AGENT_ACCESS_TOKEN=${LW_AGENT_ACCESS_TOKEN}"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
  deploy-ecs:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: tf-ecs/
      - terraform/validate:
          path: tf-ecs/
      - terraform/plan:
          path: tf-ecs/
      - terraform/apply:
          path: tf-ecs/
workflows:
  skywalker:
    jobs:
      - deploy-ecr
      - docker-build-push:
          requires:
            - deploy-ecr
      - deploy-ecs:
          requires:
            - docker-build-push